CREATE DATABASE IF NOT EXISTS user_schema;
USE user_schema;
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) DEFAULT NULL,
    email VARCHAR(50) DEFAULT NULL,
    password VARCHAR(200) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    salt VARCHAR(200) DEFAULT NULL,
    PRIMARY KEY (id)
)